### ISSUE TITLE
Plz for error

### ISSUE THREAD

**Issue by cookiesze** [jolyjokerz/koCART#1]
A PHP Error was encountered

Severity: Notice

Message: Only variable references should be returned by reference

Filename: core/Common.php

Line Number: 257

Fatal error: Uncaught Error: Call to undefined function mysql_pconnect() in C:\xampp\htdocs\ecom6\system\database\drivers\mysql\mysql_driver.php:91 Stack trace: #0 C:\xampp\htdocs\ecom6\system\database\DB_driver.php(115): CI_DB_mysql_driver->db_pconnect() #1 C:\xampp\htdocs\ecom6\system\database\DB.php(148): CI_DB_driver->initialize() #2 C:\xampp\htdocs\ecom6\system\core\Loader.php(346): DB(Array, NULL) #3 C:\xampp\htdocs\ecom6\application\helpers\language_helper.php(8): CI_Loader->database() #4 C:\xampp\htdocs\ecom6\system\core\Loader.php(527): include_once('C:\xampp\htdocs...') #5 C:\xampp\htdocs\ecom6\system\core\Loader.php(1154): CI_Loader->helper(Array) #6 C:\xampp\htdocs\ecom6\system\core\Loader.php(152): CI_Loader->_ci_autoloader() #7 C:\xampp\htdocs\ecom6\system\core\Controller.php(51): CI_Loader->initialize() #8 C:\xampp\htdocs\ecom6\application\core\MY_Controller.php(9): CI_Controller->__construct() #9 C:\xampp\htdocs\ecom6\application\controllers\home.php(8): KoController->__construct() #10 C:\xampp\htdocs\ec in C:\xampp\htdocs\ecom6\system\database\drivers\mysql\mysql_driver.php on line 91

**Comment by kzorluoglu** [comment]
#2

**Comment by kzorluoglu** [comment]
#2
